controller_list:
  - name: fake_braccio_arm_controller
    joints:
      - base
      - shoulder
      - elbow
      - wrist_pitch
      - wrist_roll
  - name: fake_hand_controller
    joints:
      - gripper_movable
initial:  # Define initial robot poses.
  - group: braccio_arm
    pose: default